# Generated by Django 3.0.2 on 2021-03-07 08:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupforum',
            fields=[
                ('namegroup', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descgroup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('nametags', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('descproblem', ckeditor.fields.RichTextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Groupforum')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Tags')),
            ],
        ),
    ]
