# Generated by Django 3.0.2 on 2021-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='tags',
        ),
        migrations.AddField(
            model_name='forum',
            name='tags',
            field=models.ManyToManyField(to='forum.Tags'),
        ),
    ]
