# Generated by Django 3.0.2 on 2021-03-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210307_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='gambar',
            field=models.ImageField(default='', upload_to='gambar/'),
            preserve_default=False,
        ),
    ]
